- name: Configuring Nagios
  docker_container:
    name: nagios-monitoring
    image: jasonrivers/nagios:latest
    state: started 
    ports:
      - 8005:80
#      - 4000:80
#      - 4001:3001
    volumes:
      - nagiosetc:/opt/nagios/etc
      - nagiosvar:/opt/nagios/var
      - customplugins:/opt/Custom-Nagios-Plugins
      - nagiosgraphvar:/opt/nagiosgraph/var
      - nagiosgraphetc:/opt/nagiosgraph/etc


#    volumes:
#      - grafana-storage:/var/lib/grafana
#- name: Waits for port 5432 of IP to close active connections, don't start checking for 10 seconds
#  wait_for:
#    host: 34.201.250.199
#    port: 5432
#    delay: 10
#    state: drained
#
