- name: Configuring Grafana
  docker_container:
    name: grafana-insights
    image: bmtsys/insights
    state: started 
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
#- name: Waits for port 5432 of IP to close active connections, don't start checking for 10 seconds
#  wait_for:
#    host: 34.201.250.199
#    port: 5432
#    delay: 10
#    state: drained
#
