---
  - name: Provision an EC2 Instances
    hosts: localhost
    connection: local
    gather_facts: False
    tags: provisioning
    # Necessary Variables for creating/provisioning the EC2 Instance
    vars:
      group_id:
        - sg-0643ee3b3d085ce6d
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 8
          delete_on_termination: True
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 8
          delete_on_termination: True
    tasks:
      - name: Launch the first EC2 Instance
        local_action: ec2
                      count=3
                      aws_access_key=AKIAIPPXPLG77SB2DIWQ
                      aws_secret_key=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
                      group_id={{ group_id }}
                      instance_type=t2.micro
                      image=ami-cd0f5cb6
                      wait=false
                      region=us-east-1
                      keypair=bmtsys
                      vpc_subnet_id=subnet-ec2497b6
                      assign_public_ip=no
                      volumes={{ volumes }}
                      zone=us-east-1c
                      termination_protection=no
        register: ec2
        retries: "2"
        delay: "3"
        with_items: ec2.instances
        no_log: False
