- name: install Kong API Gateway
  docker_container:
    name: kongapigateway
    image: kong:0.14.1
    env:
#      KONG_PG_HOST: 34.201.250.199
      KONG_PG_HOST: 3.83.90.229
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PG_PASSWORD: kong
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
    privileged: true
#- name: Create Systemd Unit File as docker-kongapigateway.service
#  template: src=systemd.j2 dest=/etc/systemd/system/kongapigateway.service
- name: reload systemd daemon
  command: systemctl daemon-reload

#- name: Start & Enable docker-kongapigateway service
#  service:
#    name: kongapigateway
#    state: started
#    enabled: yes

- name: check container status
  command: docker ps
  register: result
- debug: var=result.stdout
- pause:
    seconds: 20
