- name: Konga Kong GUI
  docker_container:
    name: konggui
    image: bmtsys/konga_bmtech
    state: started 
#    restart: 'always'
#    network_mode: kong-net
    ports:
      - 1337:1337
    env:
      DB_ADAPTER: postgres
#      DB_HOST: 34.201.250.199
      DB_HOST: 3.83.90.229
      DB_USER: kong
      KONGA_HOOK_TIMEOUT: 120000
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      DB_DATABASE: konga_db
      NODE_ENV: production
#    links:
#      - kong-database
- name: Waits for port 5432 of IP to close active connections, don't start checking for 10 seconds
  wait_for:
#    host: 34.201.250.199
    host: 3.83.90.229
    port: 5432
    delay: 10
    state: drained

