- name: Configuring Portainer for docker container management
  docker_container:
    name: portainer
    image: portainer/portainer
    state: started 
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
#- name: Waits for port 5432 of IP to close active connections, don't start checking for 10 seconds
#  wait_for:
#    host: 34.201.250.199
#    port: 5432
#    delay: 10
#    state: drained
#
