- name: Configuring wazuh
  docker_container:
    name: wazuh
    image: wazuh/wazuh
    state: started 
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"



